---
title: fonts.aidensymes.com
timezone: UTC
collections:
  fonts:
    title: Fonts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: fonts
  values:
    layout: font
tagline: Display fonts by Aiden Symes.
description: Display fonts by Aiden Symes.
